---
- name: Add Nginx PPA
  apt_repository:
    repo: "{{ nginx_ppa }}"
    update_cache: yes

- name: Install Nginx
  apt:
    name: "{{ nginx_package }}"
    state: "present"
    cache_valid_time: "3600"

- name: Create SSL directory
  file:
    mode: 0700
    path: "{{ nginx_path }}/ssl"
    state: directory

- name: Generate strong unique Diffie-Hellman group.
  command: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: "{{ nginx_path }}/ssl"
    creates: "{{ nginx_path }}/ssl/dhparams.pem"
  notify: reload nginx
  tags: [diffie-hellman, letsencrypt, nginx-includes, nginx-sites]

- name: Copy h5bp configs
  copy:
    src: templates/h5bp
    dest: "{{ nginx_path }}"
  notify: reload nginx

- name: Copy drop config
  template:
    src: drop.conf.j2
    dest: "{{ nginx_path }}/conf.d/drop.conf"
  notify: reload nginx

- name: Create nginx.conf
  template:
    src: "{{ nginx_conf }}"
    dest: "{{ nginx_path }}/nginx.conf"
  notify: reload nginx
  tags: nginx-includes

- name: Disable default server
  file:
    path: "{{ nginx_path }}/sites-enabled/default"
    state: absent
  notify: reload nginx

- name: Enable Nginx to start on boot
  service:
    name: nginx
    enabled: yes
    state: started
    use: service
