---
- name: Set ansible_python_interpreter
  hosts: production_servers
  gather_facts: false
  remote_user: ubuntu
  become: true
  roles:
    - { role: python_interpreter, tags: [always] }

- name: Install server
  hosts: production_servers
  remote_user: ubuntu
  gather_facts: true
  become: true
  roles:
    - { role: 'common' }
    #- { role: 'nginx' }
    #- { role: 'apache' }
    #- { role: 'php' }
    #- { role: 'docker' }
    #- { role: 'certbot', domains: ['geekodour.xyz','*.geekodour.xyz']}
    #- { role: 'blog', domain: 'geekodour.xyz', rootdir: '/srv/www/blog/public'}
    #- { role: 'ishani', domain: 'ishani.geekodour.xyz', rootdir: '/srv/www/ishani' }
    ##- { role: 'dummy', domain: 'dummy.geekodour.xyz', rootdir: '/srv/www/dummy' }
    ##- { role: 'dummy2', domain: 'dummy2.geekodour.xyz', rootdir: '/srv/www/dummy2' }
    #- { role: 'dokuwiki', domain: '*.geekodour.xyz'}
    #- { role: 'wikianimal', domain: 'wiki.geekodour.xyz' }
    #- { role: 'prometheus', domain: 'prom.geekodour.xyz' }
    #- { role: 'alertmanager', domain: 'alerts.geekodour.xyz' }
    - { role: 'grafana', domain: 'grafana.geekodour.xyz' }
    #- { role: 'firewall' }
