---
- name: Set ansible_python_interpreter
  hosts: production_servers
  gather_facts: false
  remote_user: ubuntu
  become: true
  roles:
    - { role: python_interpreter, tags: [always] }

- name: Install server
  hosts: production_servers
  remote_user: ubuntu
  gather_facts: false
  become: true
  roles:
    #- { role: 'nginx' }
    #- { role: 'certbot', domains: ['geekodour.xyz','*.geekodour.xyz']}
    #- { role: 'common' }
    - { role: 'blog', domain: 'geekodour.xyz', rootdir: '/srv/www/blog/public'}
    #- { role: 'ishani', domain: 'ishani.geekodour.xyz' }
    #- { role: 'dokuwiki' }
    #- { role: 'wikianimal', domain: 'wiki.geekodour.xyz' }
    #- { role: 'prometheus' }
    #- { role: 'alertmanager' }
    #- { role: 'grafana', domain: 'probe.geekodour.xyz' }
    #- { role: 'znc' }
    #- { role: 'firewall' }
