---
- name: Set ansible_python_interpreter
  hosts: production_servers
  gather_facts: false
  remote_user: ubuntu
  become: true
  roles:
    - { role: python_interpreter, tags: [always] }

- name: Install server
  hosts: production_servers
  remote_user: ubuntu
  gather_facts: false
  become: true
  roles:
    - { role: 'nginx' }
    #- { role: 'backup' }
