---
- name: 'Create blog web directory'
  file:
    path: '/srv/www/blog'
    state: directory
    owner: web
    group: www-data

- name: 'Clone blog'
  become_user: 'web'
  git:
    repo: 'https://github.com/geekodour/blog.git'
    dest: '/srv/www/blog'
