---
- name: restart alertmanager
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted

- name: reload alertmanager
  become: true
  systemd:
    name: alertmanager
    state: reloaded

- name: reload nginx
  command: nginx -t
  notify: perform nginx reload

- name: perform nginx reload
  service:
    name: nginx
    state: restarted
