---
#########################################
## BASIC CONFIGURATION
#########################################
- name: configure prometheus
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
    validate: "/usr/local/bin/promtool check config %s"
  notify:
    - reload prometheus

#########################################
## FILE SERVICE DISCOVERY
#########################################
- name: check if instances.json already exist
  stat:
    path: '{{ prometheus_targets_dir }}/instances.json'
  register: instancesjson
  tags:
    - file_sd

- name: copy if file_sd backup exist
  unarchive:
    src: "targets.bak.tar"
    dest: '{{ prometheus_targets_dir }}'
    owner: root
    group: prometheus
    mode: 0640
    extra_opts: ["--strip-components=1"]
  when: use_backup
  tags:
    - file_sd

- name: copy default file_sd
  copy:
    content: '[]'
    dest: '{{ prometheus_targets_dir }}/instances.json'
    owner: root
    group: prometheus
    mode: 0640
  when: not use_backup and not instancesjson.stat.exists
  tags:
    - file_sd

#########################################
## ALERT RULES
#########################################
- name: copy alert rules
  copy:
    src: "{{ item }}"
    dest: '{{ prometheus_config_dir }}/alerts/'
    owner: root
    group: prometheus
    mode: 0640
  with_fileglob:
    - '{{ role_path }}/files/alerts/*.yml'
  notify:
    - reload prometheus
  tags:
    - update_alertrules
