---
- name: 'update apt cache'
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: 'install common packages'
  apt:
    name: '{{ item.name }}'
    state: 'present'
  with_items:
    - {name: git}
    - {name: build-essential}
    - {name: gcc}

- name: 'Create www-data group'
  group:
    name: www-web
    state: present

- name: 'Create web user'
  user:
    name: web
    group: www-web
    create_home: false

- name: 'Create www directory'
  file:
    path: /srv/www/
    owner: web
    group: www-data
    state: directory

#- include: ufw.yml
